title: Ayaz Ali
description: Portfolio of Ayaz Ali - Python Developer, Machine Learning Engineer, and Data Scientist.
baseurl: "" # Leave blank if your site is at the root of the domain.
url: "" # Your site's full URL (e.g., https://example.com).