title: Ayaz Ali
description: Portfolio of Ayaz Ali - Python Developer, Machine Learning Engineer, and Data Scientist.
baseurl: "Portfolio-with-Ruby" # Leave blank if your site is at the root of the domain.
url: "https://github.com/Ayaz-75/Portfolio-with-Ruby" # Your site's full URL (e.g., https://example.com).
